### ISSUE TITLE
2018 WV General Election Precinct Results issues

### ISSUE THREAD

**Issue by Iakhnis** [openelections/openelections-data-wv#34]
County totals do not match for Senate candidates in the following counties:

- [x] Fayette county, Morrisey 5370 (should be 5160)
- [x] Lewis county, Manchin 2329 (should be 2326)
- [x] Ritchie county, Manchin 1081 (should be 1082)
- [x] Ritchie county, Morrisey 1962 (should be 1961)
- [x] Wetzel, Manchin 2498 (should be 2518)

**Comment by dwillis** [comment]
Thanks! These are fixed now.
