### ISSUE TITLE
Fix 2016 general Kanawha precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-wv#5]
The results in the [state CSV](https://github.com/openelections/openelections-data-wv/blob/master/2016/20161108__wv__general__kanawha__precinct.csv) contain multiple errors. Fix them using [county's official canvass](https://s3.amazonaws.com/tw-desk/i/276868/attachment/999999999.20161115215809495.999999999.20161115215809495Zng41.htm).

**Comment by frankenberry** [comment]
Hi,
Were you able to get precinct data for Kanawha into a csv?

**Comment by dwillis** [comment]
It's right here: https://github.com/openelections/openelections-data-wv/blob/master/2016/20161108__wv__general__kanawha__precinct.csv
