### ISSUE TITLE
Fix Cabell 2016 general precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-wv#6]
The results in the [state CSV](https://github.com/openelections/openelections-data-wv/blob/master/2016/20161108__wv__general__cabell__precinct.csv) have 0 votes for most precincts. Fix them using [county's official canvass](https://github.com/openelections/openelections-sources-wv/blob/master/2016/Cabell%202016%20Gen.%20Pct%20Results.txt).

**Comment by lephead** [comment]
If anyone wants to do this, here is one I have started down thru prec 19 and only 52 to go!

[2016 cabell wv.xlsx](https://github.com/openelections/openelections-data-wv/files/1213729/2016.cabell.wv.xlsx)
